# coding: utf-8

"""
    Chat API SDK

    The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sale@chat-api.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import whatsapp
from whatsapp.api.2_messages_api import 2MessagesApi  # noqa: E501
from whatsapp.rest import ApiException


class Test2MessagesApi(unittest.TestCase):
    """2MessagesApi unit test stubs"""

    def setUp(self):
        self.api = whatsapp.api.2_messages_api.2MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_forward_message(self):
        """Test case for forward_message

        Forwarding messages to a new or existing chat.  # noqa: E501
        """
        pass

    def test_get_messages(self):
        """Test case for get_messages

        Get a list of messages.  # noqa: E501
        """
        pass

    def test_send_contact(self):
        """Test case for send_contact

        Sending a contact or contact list to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_file(self):
        """Test case for send_file

        Send a file to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_link(self):
        """Test case for send_link

        Send text with link and link's preview to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_location(self):
        """Test case for send_location

        Sending a location to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_message(self):
        """Test case for send_message

        Send a message to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_ptt(self):
        """Test case for send_ptt

        Send a ptt-audio to a new or existing chat.  # noqa: E501
        """
        pass

    def test_send_v_card(self):
        """Test case for send_v_card

        Sending a vcard to a new or existing chat.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
