# coding: utf-8

"""
    Chat API SDK

    The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sale@chat-api.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import whatsapp
from whatsapp.api.ban_api import BanApi  # noqa: E501
from whatsapp.rest import ApiException


class TestBanApi(unittest.TestCase):
    """BanApi unit test stubs"""

    def setUp(self):
        self.api = whatsapp.api.ban_api.BanApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ban_test(self):
        """Test case for ban_test

        Test ban settings  # noqa: E501
        """
        pass

    def test_get_ban_settings(self):
        """Test case for get_ban_settings

        Get settings  # noqa: E501
        """
        pass

    def test_set_ban_settings(self):
        """Test case for set_ban_settings

        Set settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
