# coding: utf-8

"""
    Chat API SDK

    The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sale@chat-api.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import whatsapp
from whatsapp.models.create_group_action import CreateGroupAction  # noqa: E501
from whatsapp.rest import ApiException


class TestCreateGroupAction(unittest.TestCase):
    """CreateGroupAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateGroupAction(self):
        """Test CreateGroupAction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whatsapp.models.create_group_action.CreateGroupAction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
