# coding: utf-8

"""
    Chat API SDK

    The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sale@chat-api.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import whatsapp
from whatsapp.api.queues_api import QueuesApi  # noqa: E501
from whatsapp.rest import ApiException


class TestQueuesApi(unittest.TestCase):
    """QueuesApi unit test stubs"""

    def setUp(self):
        self.api = whatsapp.api.queues_api.QueuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clear_actions_queue(self):
        """Test case for clear_actions_queue

        Clear outbound actions queue.  # noqa: E501
        """
        pass

    def test_clear_messages_queue(self):
        """Test case for clear_messages_queue

        Clear outbound messages queue.  # noqa: E501
        """
        pass

    def test_show_actions_queue(self):
        """Test case for show_actions_queue

        Get outbound messages queue.  # noqa: E501
        """
        pass

    def test_show_messages_queue(self):
        """Test case for show_messages_queue

        Get outbound messages queue.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
